### PR TITLE
feat(schema): soft watchdog warning for long-running schema migrations

### PR DESCRIPTION
**Pull request by quad341**
## Summary

Adds a soft, WARN-only watchdog for schema migrations: if a single migration
step runs past a configurable threshold (default 5m via
`BEADS_MIGRATION_WATCHDOG_INTERVAL`), logs a warning, repeating on each
interval until the step completes. No hard circuit breaker, no migration
abort — purely observational, so an operator watching stderr during a long
migration (e.g. a full-table backfill) gets a heartbeat instead of silence.

- `internal/storage/schema/schema.go`: `runMigrationWithWatchdog` +
  `migrationWatchdogIntervalDuration` (env-configurable interval, defaults to
  5m on unset/empty/invalid values)
- `internal/storage/schema/migration_watchdog_test.go`: new test file

## Review

Two-round review (be-sogif). Round 1 requested changes on a dangling doc
citation in the new comment; round 2 replaces it with two independently
verified citations (an existing `store.go` comment, verbatim-matched, and a
closed bead's `close_reason` prose) and passed clean. Two non-blocking minor
findings were carried forward by explicit reviewer decision (see full gate
record) — a cosmetic parity gap with `store.go`'s duration-parsing
convention, and a missing lower-bound clamp on the env var matching that same
existing convention's behavior (not a regression this diff introduces).

## Test plan

- [x] `go test -v -count=1 ./internal/storage/schema/...` — 237 PASS, 0 FAIL,
      0 SKIP, independently re-run on the deployed commit and verified via
      `-v` output (not exit code alone)
- [x] All 6 diff-relevant tests confirmed PASS by name
      (`TestRunMigrationWithWatchdog_*` x5, `TestMigrationWatchdogIntervalDuration`)
- [x] `gofmt -l`, `go vet ./...`, `go build ./...` clean (per review)

### CODE REVIEW

**Review by bee-ghosttrack — CHANGES_REQUESTED** [review]
**Verdict: MERGE-AFTER-FIXES** (bee, reviewed at 5672ce51f).

Mechanically this is good: `-race` clean, `fn` receives the caller's exact ctx (your `_ContextUnaffected` test proves it), error passthrough exact, the goroutine is joined before return so nothing races `runMigrations`' own writes. Red/green confirmed — the test file alone on `origin/main` fails to compile (`undefined: runMigrationWithWatchdog`), and on your head 6/6 pass (`BEADS_TEST_SKIP=dolt go test ./internal/storage/schema/... -run 'TestRunMigrationWithWatchdog|TestMigrationWatchdogIntervalDuration' -count=1`, plus a `-race` rerun). Not subsumed by and doesn't conflict with #6022 (that changed the converged fastpath, not the exec loop); merges clean on current main.

Two things before I merge:
1. The dangling citation round 2 was supposed to remove is still there. `runMigrationWithWatchdog`'s doc comment says "See `engdocs/plans/be-m65rs-migration-watchdog-scoping.md`" — that path doesn't exist in this repo and neither does `engdocs/plans/`. The replacement landed on the call-site comment only. Point it at `bd show be-m65rs` the way the call site does, or drop the sentence.
2. `stderr` in this package is `io.Discard` whenever `os.Stderr` isn't a terminal (`schema.go:29-37`). So the watchdog emits nothing under `bd serve`, systemd, CI, or any piped invocation — the cases where a silent 20-minute migration is actually alarming. On a tty it works fine. Either scope the comment to "interactive runs" or send the WARN somewhere that survives a non-tty.

Nits: `BEADS_MIGRATION_WATCHDOG_INTERVAL=300` falls back to the default rather than meaning 300s, unlike `store.go`'s `parseTimeout` you're following (you flagged this); `d > 0` is the only floor; and a new user-facing env var + new WARN line would usually earn a CHANGELOG `### Added` bullet.

**Review by bee-ghosttrack — APPROVED** [review]
Round 2 (bee), reviewed at `03859b46c` (post-rebase; I checked the rebase was CHANGELOG-only — `schema.go`'s content is what your SHA table says it is).

**Verdict: MERGE.** Both blockers are fixed, the behavioral one has a test that actually bites, and the nit you declined is declined for the right reason.

1. **Dangling citation — fixed.** `runMigrationWithWatchdog`'s doc now says `bd show be-m65rs`. `grep -rn "engdocs/plans" --include=*.go .` is empty repo-wide, and I confirmed the defect was real at the previous head (`git checkout b391e3c95 -- internal/storage/schema/schema.go` → `:101` still named the nonexistent file).
2. **Silent off a tty — fixed at the wiring, not just the helper.** `watchdogStderr` (`schema.go:39-50`) is ungated `os.Stderr` and `schema.go:1765` passes it; `stderr` keeps its terminal gate for the progress lines. Your precedent point holds — `remote_migrate_gate.go:439,454`, `smart_remote_migrate_gate.go:354,370`, `schema.go:234,291` all write ungated already. Red/green: the head's test file over the pre-fix `schema.go` fails to build (`undefined: watchdogStderr` ×3); on the head, PASS. `TestRunMigrationsWatchdogSurvivesNonTTY` asserting through `runMigrations` rather than on the package var is what makes that proof worth anything.
3. **Bare seconds — fixed, and it is exact parity.** `migrationWatchdogIntervalDuration` (`schema.go:82-98`) matches `internal/storage/dolt/store.go:564-582` branch for branch. Mutation check: deleting the `raw+"s"` branch fails `TestMigrationWatchdogIntervalDuration/bare_seconds_treated_as_seconds` (`= 5m0s; want 1m30s`) and `/bare_seconds_larger_than_default` (`= 5m0s; want 10m0s`). And you were right to be corrected on `300` — it is the default, so it could not have distinguished the two behaviors; `90`/`600` are the right table values.
4. **`d > 0` as the only floor — I concede.** `parseTimeout` has the same single floor, and diverging is what produced item 3 in the first place. A real minimum should land on both at once; happy to take that as a separate change if you still want one.
5. **CHANGELOG — good.** It names the env var, both accepted formats, the not-a-circuit-breaker contract and the deliberate non-gating.

Your `docs/reference/configuration.md` deferral is also right, and I checked rather than assumed: `docs/cli-docs.pin` is `v1.2.2` and `engdocs/decisions/2026-07-17-docs-release-pin.md` decision 1 says hand-written pages document the released binary and main-only features are not documented. The row belongs with the pin bump.

Nothing the fix round broke. `watchdogStderr` being a package var that two tests swap is safe here — no test in `internal/storage/schema` calls `t.Parallel`.

Commands: `go build ./...` rc 0; `go vet ./internal/storage/schema/...` rc 0; `gofmt -l internal/storage/schema/` empty; `BEADS_TEST_SKIP=dolt go test ./internal/storage/schema/... -run 'TestRunMigrationWithWatchdog|TestMigrationWatchdogIntervalDuration|TestRunMigrationsWatchdogSurvivesNonTTY' -count=1 -v` → ok 0.847s, 7 top-level PASS / 0 FAIL / 0 SKIP; `git merge-tree --write-tree origin/main <head>` clean on `c0d8da42d`. CI green at head on Conformance, Cross-Version Smoke, Migration Harness and Regression.
